import type { AllowedAction, ConversationState } from './types.js';

const transitions: Record<ConversationState, readonly ConversationState[]> = {
  IDLE: ['SELECT_SERVICE'],
  SELECT_SERVICE: ['RENEWAL_PASSPORT_CONDITION', 'REQUEST_LOCATION', 'SELECT_APPLICANT_TYPE', 'SELECT_GROUP_SIZE'],
  SELECT_APPLICANT_TYPE: ['REQUEST_LOCATION', 'SELECT_SERVICE'],
  SELECT_GROUP_SIZE: ['REVIEW_GROUP_APPLICANTS', 'SELECT_SERVICE'],
  REVIEW_GROUP_APPLICANTS: ['REQUEST_LOCATION', 'SELECT_GROUP_SIZE'],
  RENEWAL_PASSPORT_CONDITION: ['RENEWAL_INFORMATION_CHANGE', 'SELECT_SERVICE'],
  RENEWAL_INFORMATION_CHANGE: ['REQUEST_LOCATION', 'RENEWAL_PASSPORT_CONDITION'],
  REQUEST_LOCATION: ['FINDING_OFFICES', 'SELECT_OFFICE'],
  FINDING_OFFICES: ['SELECT_OFFICE', 'ERROR'],
  SELECT_OFFICE: ['SELECT_DATE', 'NO_SLOT_AVAILABLE', 'REQUEST_LOCATION'],
  SELECT_DATE: ['SELECT_TIME', 'NO_SLOT_AVAILABLE', 'SELECT_OFFICE'],
  SELECT_TIME: ['PREPARING_FORM', 'SELECT_DATE'],
  NO_SLOT_AVAILABLE: ['CONFIGURE_SLOT_WATCH', 'SELECT_OFFICE', 'SELECT_DATE'],
  CONFIGURE_SLOT_WATCH: ['SLOT_WATCH_ACTIVE', 'NO_SLOT_AVAILABLE'],
  SLOT_WATCH_ACTIVE: ['SLOT_OFFER_AVAILABLE', 'SELECT_OFFICE'],
  SLOT_OFFER_AVAILABLE: ['PREPARING_FORM', 'SLOT_WATCH_ACTIVE'],
  PREPARING_FORM: ['REVIEW_FORM', 'ERROR'],
  REVIEW_FORM: ['SELECT_PROCESSING_TYPE', 'PREPARING_FORM', 'ERROR'],
  SELECT_PROCESSING_TYPE: ['REVIEW_APPOINTMENT', 'REVIEW_FORM'],
  REVIEW_APPOINTMENT: ['HOLDING_SLOT', 'SELECT_TIME'],
  HOLDING_SLOT: ['SELECT_PAYMENT_METHOD', 'SELECT_TIME', 'ERROR'],
  SELECT_PAYMENT_METHOD: ['PAYMENT_PENDING', 'HOLDING_SLOT'],
  PAYMENT_PENDING: ['PAYMENT_VERIFYING', 'PAYMENT_FAILED', 'SELECT_PAYMENT_METHOD'],
  PAYMENT_VERIFYING: ['PAYMENT_SUCCESSFUL', 'PAYMENT_FAILED'],
  PAYMENT_SUCCESSFUL: ['APPOINTMENT_CONFIRMED'],
  PAYMENT_FAILED: ['SELECT_PAYMENT_METHOD', 'PAYMENT_PENDING'],
  APPOINTMENT_CONFIRMED: ['APPOINTMENT_COMPLETED'],
  APPOINTMENT_COMPLETED: ['PASSPORT_UNDER_REVIEW'],
  PASSPORT_UNDER_REVIEW: ['PASSPORT_APPROVED', 'ADDITIONAL_REQUIREMENT'],
  ADDITIONAL_REQUIREMENT: ['PASSPORT_UNDER_REVIEW'],
  PASSPORT_APPROVED: ['PASSPORT_IN_PRODUCTION'],
  PASSPORT_IN_PRODUCTION: ['PASSPORT_DISPATCHED'],
  PASSPORT_DISPATCHED: ['PASSPORT_READY_FOR_PICKUP'],
  PASSPORT_READY_FOR_PICKUP: ['PASSPORT_CLAIMED'],
  PASSPORT_CLAIMED: [],
  ERROR: ['IDLE', 'SELECT_SERVICE', 'SELECT_OFFICE'],
};

const actionByState: Partial<Record<ConversationState, readonly AllowedAction[]>> = {
  REQUEST_LOCATION: ['NONE', 'REQUEST_LOCATION_PERMISSION', 'FIND_NEARBY_OFFICES'],
  FINDING_OFFICES: ['NONE', 'FIND_NEARBY_OFFICES'],
  SELECT_OFFICE: ['NONE', 'LOAD_AVAILABLE_DATES'],
  SELECT_DATE: ['NONE', 'LOAD_AVAILABLE_TIMES'],
  SELECT_TIME: ['NONE', 'PREPARE_APPLICATION_FORM'],
  NO_SLOT_AVAILABLE: ['NONE', 'CREATE_SLOT_WATCH', 'FIND_NEARBY_OFFICES'],
  CONFIGURE_SLOT_WATCH: ['NONE', 'CREATE_SLOT_WATCH'],
  SLOT_OFFER_AVAILABLE: ['NONE', 'ACCEPT_SLOT_OFFER'],
  REVIEW_APPOINTMENT: ['NONE', 'HOLD_APPOINTMENT_SLOT'],
  SELECT_PAYMENT_METHOD: ['NONE', 'CREATE_PAYMENT_SESSION'],
  PAYMENT_PENDING: ['NONE', 'CHECK_PAYMENT_STATUS'],
  PAYMENT_VERIFYING: ['NONE', 'CHECK_PAYMENT_STATUS'],
  PAYMENT_SUCCESSFUL: ['NONE', 'CONFIRM_APPOINTMENT'],
  APPOINTMENT_CONFIRMED: ['NONE', 'LOAD_PASSPORT_JOURNEY'],
  PASSPORT_READY_FOR_PICKUP: ['NONE', 'SET_PICKUP_REMINDER'],
};

export function canTransition(from: ConversationState, to: ConversationState): boolean {
  return from === to || transitions[from].includes(to);
}

export function assertTransition(from: ConversationState, to: ConversationState): void {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid conversation transition: ${from} -> ${to}`);
  }
}

export function isActionAllowed(state: ConversationState, action: AllowedAction): boolean {
  if (action === 'NONE') return true;
  return (actionByState[state] ?? []).includes(action);
}

export { transitions };
